"""Initial migration.

Revision ID: ca9eb135760a
Revises: 
Create Date: 2022-06-23 01:03:24.667378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9eb135760a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=35), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=21), nullable=True),
    sa.Column('pic', sa.String(length=51), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('otp_timing', sa.DateTime(), nullable=True),
    sa.Column('otp', sa.String(length=7), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notification_id', sa.String(length=68), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blocks',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=35), nullable=True),
    sa.Column('user2', sa.String(length=35), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=2000), nullable=True),
    sa.Column('msg_type', sa.String(length=6), nullable=True),
    sa.Column('username', sa.String(length=35), nullable=True),
    sa.Column('get_user', sa.String(length=35), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['detail.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('blocks')
    op.drop_table('detail')
    # ### end Alembic commands ###
